/**
 * When a CMS image should be replaced by one this site baked itself.
 *
 * THE PROBLEM (2026-09-17). The "coming from out of town" band on /contact is
 * an `imageTextSection` whose picture is a screenshot of Google Maps, uploaded
 * to the CMS. This site draws its own terrain map of the course, bakes a still
 * of it for the home page, and then, two pages later, shows a visitor somebody
 * else's picture of the same city. `npm run map-region` now bakes the same view
 * from our own map, with The Oval, downtown and CVG pinned in the map's own
 * marker style. What was left was getting the page to use it.
 *
 * WHY THIS IS A RULE AND NOT A FIELD. Three options were on the table.
 *   - Key the override off the block's `_key`. Rejected outright: a key is
 *     data, it is regenerated by the seed script, and a rule that reads one is
 *     a rule that breaks silently the next time content is re-seeded.
 *   - Add a `localPoster` boolean to the imageTextSection schema. Cleaner in
 *     the abstract, and it is what we would do if the editor were about to
 *     tick it. But the schema change ships dark: until somebody opens the
 *     Studio and ticks the box, the page still serves the Google screenshot,
 *     which is the entire thing being fixed. A fix that depends on a human
 *     doing something is not a fix yet.
 *   - This: a rule about what the block SAYS, not about which block it is.
 *
 * THE RULE, stated plainly: an image-and-text block whose call to action sends
 * the reader to Google Maps is a block about where things are, and a block
 * about where things are should show this site's map rather than a picture of
 * the one it is linking to. It is derived from the content, so it survives a
 * re-seed, it is one predicate with a test around it, and it stops applying by
 * itself the day that CTA changes.
 *
 * The CTA is untouched: "Find a hotel on Google Maps" still goes to Google
 * Maps, which is the right destination for a hotel search. Only the picture
 * changes.
 *
 * WHEN TO DELETE THIS. When the screenshot is removed from the block in the
 * Studio and replaced with nothing (the baked poster is in the code, not in the
 * CMS), this rule and the branch in ImageText.astro can both go and the block
 * can render the poster as its only image. That is a content edit nobody has
 * made yet; see docs/PENDING.md.
 */

/** The baked posters this site can put in place of a CMS image. */
export type LocalPosterKey = 'region';

/**
 * Hosts whose maps this site would rather draw itself. Matched on the host
 * plus the path, not on the whole string, so a query string the race changes
 * one day cannot switch the rule off by accident.
 */
function isGoogleMapsUrl(href: string): boolean {
  let url: URL;
  try {
    url = new URL(href);
  } catch {
    // A relative or malformed href is never an external map link.
    return false;
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return false;
  const host = url.hostname.replace(/^www\./, '').toLowerCase();
  if (host === 'maps.google.com' || host === 'goo.gl' || host === 'maps.app.goo.gl') return true;
  // google.com, google.co.uk and the rest, but only on the maps path.
  return /(^|\.)google\.[a-z.]+$/.test(host) && url.pathname.startsWith('/maps');
}

/**
 * Which baked poster, if any, an image-and-text block should show instead of
 * its CMS image.
 *
 * Takes the CTA's href and nothing else on purpose: the whole point is that the
 * rule can be read, tested and predicted from one string.
 */
export function localPosterFor(ctaHref?: string | null): LocalPosterKey | null {
  if (!ctaHref) return null;
  return isGoogleMapsUrl(ctaHref) ? 'region' : null;
}
