/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Photo = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "photo.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type Redirect = {
  _id: string;
  _type: 'redirect';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from?: string;
  to?: string;
  permanent?: boolean;
  note?: string;
};

export type SectionPreset = {
  _id: string;
  _type: 'sectionPreset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  sectionType?: string;
  section?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & EmbedSection)
    | ({
        _key: string;
      } & FounderSection)
    | ({
        _key: string;
      } & ServicesGridSection)
    | ({
        _key: string;
      } & TestimonialsSection)
    | ({
        _key: string;
      } & StorySection)
    | ({
        _key: string;
      } & ValuesSection)
    | ({
        _key: string;
      } & ProcessSection)
    | ({
        _key: string;
      } & ServiceAreaSection)
    | ({
        _key: string;
      } & GuaranteeSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & TeamSection)
    | ({
        _key: string;
      } & DynamicListSection)
  >;
  note?: string;
};

export type JournalCategory = {
  _id: string;
  _type: 'journalCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type ProcessStep = {
  _id: string;
  _type: 'processStep';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stepNumber?: number;
  title?: string;
  timeEstimate?: string;
  shortDescription?: string;
  features?: Array<string>;
  tierNote?: string;
  orderRank?: string;
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: string;
  priceNumeric?: number;
  shortDescription?: string;
  features?: Array<string>;
  bestFor?: string;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  longDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  displayOrder?: number;
  showOnHomepage?: boolean;
  ctaLabel?: string;
  orderRank?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PhilosophyPoint = {
  _id: string;
  _type: 'philosophyPoint';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  displayOrder?: number;
  orderRank?: string;
};

export type FaqCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faqCategory';
};

export type FaqItem = {
  _id: string;
  _type: 'faqItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h4';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  category?: 'Pricing & Cost' | 'The Process' | 'Logistics' | 'Service Area' | 'Getting Started';
  categoryRef?: FaqCategoryReference;
  displayOrder?: number;
  alsoShowOnProcessPage?: boolean;
};

export type FaqCategory = {
  _id: string;
  _type: 'faqCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  displayOrder?: number;
};

export type Announcement = {
  _id: string;
  _type: 'announcement';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalTitle?: string;
  message?: string;
  style?: 'info' | 'highlight' | 'urgent';
  link?: {
    label?: string;
    url?: string;
  };
  startDate?: string;
  endDate?: string;
  enabled?: boolean;
};

export type StudioPlaybook = {
  _id: string;
  _type: 'studioPlaybook';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
  guides?: Array<{
    title?: string;
    summary?: string;
    sections?: Array<{
      heading?: string;
      tone?: 'default' | 'primary' | 'positive' | 'caution';
      body?: string;
      bullets?: Array<string>;
      links?: Array<{
        label?: string;
        url?: string;
        _type: 'playbookLink';
        _key: string;
      }>;
      _type: 'playbookSection';
      _key: string;
    }>;
    _type: 'playbookGuide';
    _key: string;
  }>;
};

export type StudioNotes = {
  _id: string;
  _type: 'studioNotes';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessSummary?: string;
  idealClient?: string;
  voiceSummary?: string;
  wordsToAvoid?: Array<string>;
};

export type StudioGuide = {
  _id: string;
  _type: 'studioGuide';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  guideTitle?: string;
  guideIntro?: string;
  studioMap?: Array<{
    area?: string;
    description?: string;
    _type: 'mapRow';
    _key: string;
  }>;
  howTos?: Array<{
    title?: string;
    steps?: Array<string>;
    _type: 'howTo';
    _key: string;
  }>;
  tips?: Array<{
    heading?: string;
    tone?: 'default' | 'primary' | 'caution' | 'positive';
    body?: string;
    _type: 'tip';
    _key: string;
  }>;
};

export type NotFoundPage = {
  _id: string;
  _type: 'notFoundPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  eyebrow?: string;
  headline?: string;
  body?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
  };
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  tertiaryCtaLabel?: string;
  tertiaryCtaHref?: string;
};

export type BusinessInfo = {
  _id: string;
  _type: 'businessInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessModel?: 'in-person' | 'remote' | 'hybrid';
  city?: string;
  state?: string;
  serviceRegion?: string;
  serviceAreas?: Array<string>;
  travelFees?: Array<{
    distanceLabel?: string;
    fee?: string;
    _type: 'travelFeeTier';
    _key: string;
  }>;
  availabilityStatus?: string;
  geoLat?: number;
  geoLng?: number;
  additionalLocations?: Array<{
    city?: string;
    state?: string;
    geoLat?: number;
    geoLng?: number;
    _type: 'additionalLocation';
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  email?: string;
  phone?: string;
  navItems?: Array<
    | ({
        _key: string;
      } & NavLink)
    | {
        label?: string;
        links?: Array<{
          label?: string;
          href?: string;
          _type: 'navSubLink';
          _key: string;
        }>;
        _type: 'navGroup';
        _key: string;
      }
  >;
  footerColumns?: Array<{
    title?: string;
    links?: Array<
      | ({
          _key: string;
        } & NavLink)
      | {
          label?: string;
          href?: string;
          _type: 'footerLink';
          _key: string;
        }
    >;
    _type: 'footerColumn';
    _key: string;
  }>;
  headerCta?: {
    show?: boolean;
    label?: string;
    link?: NavLink;
  };
  showEmail?: boolean;
  showSocials?: boolean;
  showFooterSocials?: boolean;
  legalNav?: Array<
    {
      _key: string;
    } & NavLink
  >;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  availabilityStatus?: string;
  serviceAreas?: Array<string>;
  travelFees?: Array<{
    distanceLabel?: string;
    fee?: string;
    _type: 'travelFeeTier';
    _key: string;
  }>;
  socialInstagram?: string;
  socialFacebook?: string;
  socialLinks?: Array<{
    platform?:
      | 'Instagram'
      | 'Facebook'
      | 'LinkedIn'
      | 'Pinterest'
      | 'YouTube'
      | 'TikTok'
      | 'X'
      | 'Houzz'
      | 'Other';
    url?: string;
    label?: string;
    _type: 'socialLink';
    _key: string;
  }>;
  businessType?:
    | 'LocalBusiness'
    | 'ProfessionalService'
    | 'HomeAndConstructionBusiness'
    | 'LegalService'
    | 'MedicalBusiness'
    | 'HealthAndBeautyBusiness'
    | 'FoodEstablishment'
    | 'Store'
    | 'RealEstateAgent'
    | 'TravelAgency'
    | 'EducationalOrganization'
    | 'NGO';
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  footerCredit?: string;
  footerCreditUrl?: string;
  newsletter?: {
    enabled?: boolean;
    providerLabel?: string;
    formActionUrl?: string;
    audienceId?: string;
    heading?: string;
    blurb?: string;
    buttonLabel?: string;
    successMessage?: string;
    consentNote?: string;
  };
  googleBusinessUrl?: string;
  reviewsNote?: string;
  sectionVisibility?: {
    showPortfolio?: boolean;
    showJournal?: boolean;
    showShop?: boolean;
    showEDesign?: boolean;
    showGiftCertificates?: boolean;
    showPress?: boolean;
    showResources?: boolean;
    showGuides?: boolean;
    showStyleQuiz?: boolean;
    showBudgetCalculator?: boolean;
  };
  satisfactionGuarantee?: string;
};

export type HomePageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'homePage';
};

export type AboutPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'aboutPage';
};

export type ServicesPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'servicesPage';
};

export type ProcessPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'processPage';
};

export type FaqPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faqPage';
};

export type ContactPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'contactPage';
};

export type JournalPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'journalPage';
};

export type PrivacyPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'privacyPage';
};

export type PageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'page';
};

export type NavLink = {
  _type: 'navLink';
  label?: string;
  linkType?: 'internal' | 'external';
  internalPage?:
    | HomePageReference
    | AboutPageReference
    | ServicesPageReference
    | ProcessPageReference
    | FaqPageReference
    | ContactPageReference
    | JournalPageReference
    | PrivacyPageReference
    | PageReference;
  externalUrl?: string;
  href?: string;
};

export type DynamicListSection = {
  _type: 'dynamicListSection';
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  subheadRich?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  columns?: 2 | 3;
  source?: 'journal' | 'services' | 'testimonials' | 'faqs';
  limit?: number;
  cta?: CtaBlock;
};

export type TeamSection = {
  _type: 'teamSection';
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  subheadRich?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  members?: Array<{
    name?: string;
    role?: string;
    photo?: Photo;
    bio?: string;
    socialLinks?: Array<{
      label?: string;
      url?: string;
      _type: 'socialLink';
      _key: string;
    }>;
    _type: 'teamMember';
    _key: string;
  }>;
};

export type FaqItemReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faqItem';
};

export type FaqSection = {
  _type: 'faqSection';
  eyebrow?: string;
  headline?: string;
  headingAccent?: string;
  subhead?: string;
  subheadRich?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  items?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  cta?: CtaBlock;
};

export type GuaranteeSection = {
  _type: 'guaranteeSection';
  text?: string;
};

export type ServiceAreaSection = {
  _type: 'serviceAreaSection';
  eyebrow?: string;
  headline?: string;
  description?: string;
  showTravelFees?: boolean;
};

export type ProcessSection = {
  _type: 'processSection';
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  variant?: 'preview' | 'full';
  cta?: CtaBlock;
};

export type ValuesSection = {
  _type: 'valuesSection';
  eyebrow?: string;
  headline?: string;
  columns?: 2 | 3;
};

export type StorySection = {
  _type: 'storySection';
  eyebrow?: string;
  headline?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  attribution?: string;
  credentialLine?: string;
  serviceAreaLine?: string;
};

export type TestimonialReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'testimonial';
};

export type TestimonialsSection = {
  _type: 'testimonialsSection';
  eyebrow?: string;
  headline?: string;
  scriptAccent?: string;
  headingAccent?: string;
  subhead?: string;
  subheadRich?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  featuredQuote?: TestimonialReference;
  testimonialsToShow?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  attribution?: string;
};

export type ServicesGridSection = {
  _type: 'servicesGridSection';
  eyebrow?: string;
  headline?: string;
  scriptAccent?: string;
  headingAccent?: string;
  subhead?: string;
  subheadRich?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  cta?: CtaBlock;
  footnote?: string;
  variant?: 'grid' | 'list';
};

export type FounderSection = {
  _type: 'founderSection';
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  eyebrow?: string;
  headline?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  cta?: CtaBlock;
};

export type EmbedSection = {
  _type: 'embedSection';
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  embedUrl?: string;
  embedCode?: string;
  heightHint?: 'short' | 'medium' | 'tall';
};

export type LogoStripSection = {
  _type: 'logoStripSection';
  eyebrow?: string;
  headline?: string;
  logos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  layout?: 'row' | 'grid';
};

export type SpacerSection = {
  _type: 'spacerSection';
  variant?: 'ornament' | 'line' | 'space';
};

export type VideoSection = {
  _type: 'videoSection';
  url?: string;
  heading?: string;
  caption?: string;
};

export type CtaBandSection = {
  _type: 'ctaBandSection';
  eyebrow?: string;
  headline?: string;
  scriptAccent?: string;
  headingAccent?: string;
  subhead?: string;
  subheadRich?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  cta?: CtaBlock;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type StatSection = {
  _type: 'statSection';
  heading?: string;
  stats?: Array<{
    number?: number;
    suffix?: string;
    label?: string;
    _type: 'statItem';
    _key: string;
  }>;
};

export type QuoteSection = {
  _type: 'quoteSection';
  quote?: string;
  attribution?: string;
  detail?: string;
};

export type GallerySection = {
  _type: 'gallerySection';
  heading?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
    _key: string;
  }>;
  columns?: 2 | 3 | 4;
};

export type ImageTextSection = {
  _type: 'imageTextSection';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  imageSide?: 'left' | 'right';
  eyebrow?: string;
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  cta?: CtaBlock;
};

export type RichTextSection = {
  _type: 'richTextSection';
  eyebrow?: string;
  heading?: string;
  scriptAccent?: string;
  headingAccent?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  width?: 'normal' | 'narrow';
  align?: 'left' | 'center';
};

export type HeroSection = {
  _type: 'heroSection';
  eyebrow?: string;
  headline?: string;
  scriptAccent?: string;
  subhead?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  primaryCta?: CtaBlock;
  secondaryCta?: CtaBlock;
  size?: 'tall' | 'short';
};

export type FormQuestion = {
  _type: 'formQuestion';
  label?: string;
  kind?: 'text' | 'email' | 'phone' | 'textarea' | 'select' | 'checkbox';
  options?: Array<string>;
  required?: boolean;
};

export type PrivacyPage = {
  _id: string;
  _type: 'privacyPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type JournalEntryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'journalEntry';
};

export type CtaBlock = {
  _type: 'ctaBlock';
  label?: string;
  linkType?: 'internal' | 'external' | 'email' | 'phone';
  internalLink?:
    | HomePageReference
    | AboutPageReference
    | ServicesPageReference
    | ProcessPageReference
    | FaqPageReference
    | ContactPageReference
    | JournalPageReference
    | JournalEntryReference
    | PageReference;
  externalUrl?: string;
  emailAddress?: string;
  phoneNumber?: string;
  openInNewTab?: boolean;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & EmbedSection)
  >;
  addToMainNav?: boolean;
  navGroup?: 'top' | 'services' | 'resources';
  navLabel?: string;
  addToFooter?: boolean;
  archived?: boolean;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  hideFromSearch?: boolean;
  publishAt?: string;
};

export type JournalCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'journalCategory';
};

export type JournalEntry = {
  _id: string;
  _type: 'journalEntry';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
  };
  categories?: Array<
    {
      _key: string;
    } & JournalCategoryReference
  >;
  author?: string;
  publishedAt?: string;
  updatedAt?: string;
  featured?: boolean;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'lead' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<
          | {
              href?: string;
              openInNewTab?: boolean;
              _type: 'link';
              _key: string;
            }
          | {
              vendor?: string;
              url?: string;
              _type: 'sourcedFrom';
              _key: string;
            }
        >;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        size?: 'standard' | 'wide' | 'full';
        _type: 'inlineImage';
        _key: string;
      }
    | {
        quote?: string;
        attribution?: string;
        _type: 'pullQuote';
        _key: string;
      }
    | {
        beforeImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
        };
        afterImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
        };
        caption?: string;
        _type: 'beforeAfter';
        _key: string;
      }
    | {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
        };
        itemName?: string;
        vendor?: string;
        price?: string;
        url?: string;
        notes?: string;
        _type: 'sourceCard';
        _key: string;
      }
    | {
        label?: string;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'normal';
          listItem?: 'bullet';
          markDefs?: Array<{
            href?: string;
            openInNewTab?: boolean;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }>;
        _type: 'tipCallout';
        _key: string;
      }
    | {
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: 'image';
          _key: string;
        }>;
        layout?: 'grid2' | 'grid3' | 'row';
        caption?: string;
        _type: 'imageGallery';
        _key: string;
      }
    | {
        style?: 'line' | 'ornament' | 'space';
        _type: 'divider';
        _key: string;
      }
    | {
        url?: string;
        caption?: string;
        _type: 'videoEmbed';
        _key: string;
      }
  >;
  seoTitle?: string;
  seoDescription?: string;
  relatedPosts?: Array<
    {
      _key: string;
    } & JournalEntryReference
  >;
};

export type JournalPage = {
  _id: string;
  _type: 'journalPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  stickyCtaLabel?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type ContactPage = {
  _id: string;
  _type: 'contactPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  formIntroNote?: string;
  formProjectTypeOptions?: Array<string>;
  formLocationOptions?: Array<string>;
  formBudgetOptions?: Array<string>;
  formTimelineOptions?: Array<string>;
  formSourceOptions?: Array<string>;
  formFields?: Array<
    {
      _key: string;
    } & FormQuestion
  >;
  whatToExpectEyebrow?: string;
  whatToExpectHeadline?: string;
  whatToExpectContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  postInquiryRoadmap?: Array<{
    title?: string;
    body?: string;
    timeEstimate?: string;
    _type: 'roadmapStep';
    _key: string;
  }>;
  schedulingLink?: string;
  schedulingLinkLabel?: string;
  availabilityNote?: string;
  note?: string;
};

export type FaqPage = {
  _id: string;
  _type: 'faqPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  categoryOrder?: Array<string>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  secondaryCta?: CtaBlock;
  note?: string;
};

export type ProcessPage = {
  _id: string;
  _type: 'processPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & EmbedSection)
    | ({
        _key: string;
      } & ProcessSection)
    | ({
        _key: string;
      } & FaqSection)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type ServicesPage = {
  _id: string;
  _type: 'servicesPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & EmbedSection)
    | ({
        _key: string;
      } & ServicesGridSection)
    | ({
        _key: string;
      } & ServiceAreaSection)
    | ({
        _key: string;
      } & GuaranteeSection)
    | ({
        _key: string;
      } & FaqSection)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  stickyCtaLabel?: string;
  servicesListEyebrow?: string;
  servicesListHeadline?: string;
  servicesListSubhead?: string;
  serviceAreaSection?: {
    eyebrow?: string;
    headline?: string;
    description?: string;
  };
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  note?: string;
};

export type AboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & EmbedSection)
    | ({
        _key: string;
      } & StorySection)
    | ({
        _key: string;
      } & ValuesSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & TeamSection)
    | ({
        _key: string;
      } & DynamicListSection)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  storyEyebrow?: string;
  storyHeadline?: string;
  storyContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  founderPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  founderAttribution?: string;
  backgroundLine?: string;
  serviceAreaMention?: string;
  philosophyEyebrow?: string;
  philosophyHeadline?: string;
  personalEyebrow?: string;
  personalHeadline?: string;
  personalIntro?: string;
  currentlyList?: Array<{
    label?: string;
    value?: string;
    _type: 'currentlyRow';
    _key: string;
  }>;
  rapidFire?: Array<{
    prompt?: string;
    answer?: string;
    _type: 'rapidFireRow';
    _key: string;
  }>;
  localSpots?: Array<{
    name?: string;
    note?: string;
    _type: 'localSpotRow';
    _key: string;
  }>;
  beyondDesign?: string;
  candidPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  stats?: Array<{
    number?: number;
    suffix?: string;
    label?: string;
    _type: 'statItem';
    _key: string;
  }>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & EmbedSection)
    | ({
        _key: string;
      } & FounderSection)
    | ({
        _key: string;
      } & ServicesGridSection)
    | ({
        _key: string;
      } & TestimonialsSection)
    | ({
        _key: string;
      } & ProcessSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & TeamSection)
    | ({
        _key: string;
      } & DynamicListSection)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  heroPrimaryCta?: CtaBlock;
  heroSecondaryCta?: CtaBlock;
  heroRotatingWords?: Array<string>;
  heroScriptAccent?: string;
  meetFounderPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  meetFounderEyebrow?: string;
  meetFounderHeadline?: string;
  meetFounderContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  meetFounderCta?: CtaBlock;
  featuredWorkEyebrow?: string;
  featuredWorkHeadline?: string;
  featuredWorkSubhead?: string;
  featuredWorkCta?: CtaBlock;
  featuredJournalEyebrow?: string;
  featuredJournalHeadline?: string;
  featuredJournalSubhead?: string;
  featuredJournalCta?: CtaBlock;
  processPreviewEyebrow?: string;
  processPreviewHeadline?: string;
  processPreviewSubhead?: string;
  processPreviewCta?: CtaBlock;
  featuredTestimonial?: TestimonialReference;
  testimonialsEyebrow?: string;
  testimonialsHeadline?: string;
  testimonialsScriptAccent?: string;
  testimonialsSubhead?: string;
  testimonialsToShow?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  testimonialsAttribution?: string;
  servicesGridEyebrow?: string;
  servicesGridHeadline?: string;
  servicesGridScriptAccent?: string;
  servicesGridSubhead?: string;
  servicesGridCta?: CtaBlock;
  servicesGridFootnote?: string;
  serviceAreaCue?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Testimonial = {
  _id: string;
  _type: 'testimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  date?: string;
  source?: 'Facebook' | 'Google' | 'Houzz' | 'Direct (email or text)' | 'Other';
  location?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  featured?: boolean;
  sourceType?: 'Google' | 'Facebook' | 'Houzz' | 'Direct';
  reviewUrl?: string;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Photo
  | Redirect
  | SectionPreset
  | JournalCategory
  | Slug
  | ProcessStep
  | Service
  | SanityImageCrop
  | SanityImageHotspot
  | PhilosophyPoint
  | FaqCategoryReference
  | FaqItem
  | FaqCategory
  | Announcement
  | StudioPlaybook
  | StudioNotes
  | StudioGuide
  | NotFoundPage
  | BusinessInfo
  | SiteSettings
  | HomePageReference
  | AboutPageReference
  | ServicesPageReference
  | ProcessPageReference
  | FaqPageReference
  | ContactPageReference
  | JournalPageReference
  | PrivacyPageReference
  | PageReference
  | NavLink
  | DynamicListSection
  | TeamSection
  | FaqItemReference
  | FaqSection
  | GuaranteeSection
  | ServiceAreaSection
  | ProcessSection
  | ValuesSection
  | StorySection
  | TestimonialReference
  | TestimonialsSection
  | ServicesGridSection
  | FounderSection
  | EmbedSection
  | LogoStripSection
  | SpacerSection
  | VideoSection
  | CtaBandSection
  | StatSection
  | QuoteSection
  | GallerySection
  | ImageTextSection
  | RichTextSection
  | HeroSection
  | FormQuestion
  | PrivacyPage
  | JournalEntryReference
  | CtaBlock
  | Page
  | JournalCategoryReference
  | JournalEntry
  | JournalPage
  | ContactPage
  | FaqPage
  | ProcessPage
  | ServicesPage
  | AboutPage
  | HomePage
  | Testimonial
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
